Add some more fields
This currently is not reporting to VRM because it doesn't correctly
support GetValue (yet).

root@ekrano:~# dbus -y com.victronenergy.temperature.ruuvi_dd4240ee1474 /DeviceInstance GetValue
value = 25
root@ekrano:~# dbus -y com.victronenergy.temperature.virtual_dfa /DeviceInstance GetValue
Traceback (most recent call last):
  File "/usr/bin/dbus", line 374, in <module>
    ret = obj.object.get_dbus_method(method.name, iface.name)(*args)
AttributeError: 'NoneType' object has no attribute 'name'